### ISSUE TITLE
Support homebrew install

### ISSUE THREAD

**Issue by moul** [moul/docker-diff#1]

**Comment by JoeNyland** [comment]
I can create a Homebrew formula for you if you would like? All I should need is a tagged release on this repo if you could create that please.

**Comment by moul** [comment]
Thank you!

tag just pushed

**Comment by JoeNyland** [comment]
Great, thanks.

Here you go! https://github.com/Homebrew/homebrew-core/pull/10751

**Comment by moul** [comment]
Can you upload your brew config file somewhere in this repo ? I will add it to my meta repo here https://github.com/moul/homebrew-moul and update the README.md file accordingly with install instructions

**Comment by JoeNyland** [comment]
Sure https://github.com/JoeNyland/homebrew-docker/blob/b65add57bb9c9d4f55e62393e4b3249fb3356544/Formula/docker-diff.rb

**Comment by moul** [comment]
Cool, can you make a PR on this repo with instructions to install this tool using your homebrew library ?

**Comment by JoeNyland** [comment]
Do you mean instructions on how to install it from my Homebrew tap?

**Comment by moul** [comment]
Yep, completely

**Comment by JoeNyland** [comment]
Here you go: #3

**Comment by moul** [comment]
Thanks
