### ISSUE TITLE
Move to using your own Homebrew tap

### ISSUE THREAD

**Issue by JoeNyland** [moul/docker-diff#6]
Migrated from https://github.com/moul/docker-diff/commit/3000ebba18d6abd684b8b64f82df0d24429cd824#commitcomment-21254244.

It would be better for you to host your own Homebrew tap to install this script from.

As it stands, if I change the `url` or `head` in the formula from **my tap** which the [README](https://github.com/moul/docker-diff/blob/3000ebba18d6abd684b8b64f82df0d24429cd824/README.md) currently tells people to install from to, say my fork, people will be installing from my fork and not the original repo here.

I should have suggested this before I raised [the PR](https://github.com/moul/docker-diff/pull/3) that you asked for, but I've only just realised this now, sorry.

On [my tap](https://github.com/JoeNyland/homebrew-docker), [this commit](https://github.com/JoeNyland/homebrew-docker/commit/90f7cdeba17c5d9fdeefc7c3fb86e198e7f6def1) moves to install from my fork when my tap is used. If you're happy for users to install from my tap and my fork then I've got no issues with that, but I assumed you would prefer to retain control over this? 🙂

**Comment by moul** [comment]
Done, thanks for the suggestion
